### ISSUE TITLE
Build is failing for the Table package

### ISSUE THREAD

**Issue by TriangleJuice** [digipolisantwerp/acpaas-ui_angular#17]
## Describe the bug
When running `ng build table` the build fails with the following error:

```
BUILD ERROR
packages/table/src/table.ts(7,45): error TS2307: Cannot find module './lib/table/column-selector/column-selector.component'.
packages/table/src/table.ts(10,43): error TS2307: Cannot find module './lib/table/table-bar-item/table-bar-item.directive'.
packages/table/src/table.ts(11,45): error TS2307: Cannot find module './lib/table/table-bar-search/table-bar-search.directive'.
packages/table/src/table.ts(12,39): error TS2307: Cannot find module './lib/table/table-bar/table-bar.component'.
packages/table/src/table.ts(13,40): error TS2307: Cannot find module './lib/table/table-cell/table-cell.component'.
packages/table/src/table.ts(14,42): error TS2307: Cannot find module './lib/table/table-header/table-header.component'.
packages/table/src/table.ts(15,36): error TS2307: Cannot find module './lib/table/table/table.component'.

Error: packages/table/src/table.ts(7,45): error TS2307: Cannot find module './lib/table/column-selector/column-selector.component'.
packages/table/src/table.ts(10,43): error TS2307: Cannot find module './lib/table/table-bar-item/table-bar-item.directive'.
packages/table/src/table.ts(11,45): error TS2307: Cannot find module './lib/table/table-bar-search/table-bar-search.directive'.
packages/table/src/table.ts(12,39): error TS2307: Cannot find module './lib/table/table-bar/table-bar.component'.
packages/table/src/table.ts(13,40): error TS2307: Cannot find module './lib/table/table-cell/table-cell.component'.
packages/table/src/table.ts(14,42): error TS2307: Cannot find module './lib/table/table-header/table-header.component'.
packages/table/src/table.ts(15,36): error TS2307: Cannot find module './lib/table/table/table.component'.

    at Object.<anonymous> (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

packages/table/src/table.ts(7,45): error TS2307: Cannot find module './lib/table/column-selector/column-selector.component'.
packages/table/src/table.ts(10,43): error TS2307: Cannot find module './lib/table/table-bar-item/table-bar-item.directive'.
packages/table/src/table.ts(11,45): error TS2307: Cannot find module './lib/table/table-bar-search/table-bar-search.directive'.
packages/table/src/table.ts(12,39): error TS2307: Cannot find module './lib/table/table-bar/table-bar.component'.
packages/table/src/table.ts(13,40): error TS2307: Cannot find module './lib/table/table-cell/table-cell.component'.
packages/table/src/table.ts(14,42): error TS2307: Cannot find module './lib/table/table-header/table-header.component'.
packages/table/src/table.ts(15,36): error TS2307: Cannot find module './lib/table/table/table.component'.

Error: packages/table/src/table.ts(7,45): error TS2307: Cannot find module './lib/table/column-selector/column-selector.component'.
packages/table/src/table.ts(10,43): error TS2307: Cannot find module './lib/table/table-bar-item/table-bar-item.directive'.
packages/table/src/table.ts(11,45): error TS2307: Cannot find module './lib/table/table-bar-search/table-bar-search.directive'.
packages/table/src/table.ts(12,39): error TS2307: Cannot find module './lib/table/table-bar/table-bar.component'.
packages/table/src/table.ts(13,40): error TS2307: Cannot find module './lib/table/table-cell/table-cell.component'.
packages/table/src/table.ts(14,42): error TS2307: Cannot find module './lib/table/table-header/table-header.component'.
packages/table/src/table.ts(15,36): error TS2307: Cannot find module './lib/table/table/table.component'.

    at Object.<anonymous> (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```
## To Reproduce
1. Run `ng build table`
2. See error

## Expected behavior
Successful build. All other packages have no issues

## Screenshots
N/A

## OS (please complete the following information):
 - Device: MacBook Pro (Retina, 15-inch, Early 2013)
 - OS: macOS High Sierra (Version 10.13.6)
 - Browser: N/A
 - Version: N/A

## Additional context
Threw away `node_modules` and `package-lock.json`. Tried again. Same error.

**Comment by tom-odb** [comment]
Bizarre issue dit. Had de error initieel niet. Dan een keer node_modules herinstalleerd en dan had ik het ook. Wat packages geüpdatet, config aangepast, zo van die dingen, leek allemaal niet veel te helpen.
Dan de index van de table eens aangepast naar `export * from './lib/table';` (index eraf gehaald) en dan lukte de build wel.
Alles gereset, opnieuw package geïnstalleerd en zo nog eens geprobeerd en dan lukte het plots wel.

Lijkt me dus ergens een compile fout in de chain (cli -> ng-packagr -> ngc -> typescript) die verkeerde import paths oplevert. De index erafhalen is ook geen oplossing, die hebben we er net bewust achter gezet om fouten met webpack in apps of andere afnemers tegen te gaan.

Vind ook niet direct relevante issues terug, dus kan zijn dat dit verholpen is in volgende versies van de cli/ng-packagr.

Probeer nog eens node_modules en lockfiles te verwijderen en eventueel de npm cache eens te verifyen/clearen.

In ieder geval in het oog houden of dit enkel in deze package opduikt.

**Comment by TriangleJuice** [comment]
Alles gereset, `node_modules` gedeleted, `npm cache clean --force` gedaan.

Daarna `npm install`, `npm run bootstrap` en `npm run build` ⇒ zelfde error als voorheen.

Als ik de `index` eraf haal:
- dan werkt `ng build table`
- dan werkt `npm run build` nog steeds niet, maar krijg ik wel een andere error:

```
> @acpaas-ui/ngx-components@1.0.1 postbuild /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular
> node scripts/prepublish.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'cpx'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/scripts/prepublish.js:1:75)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by lievenvg** [comment]
Idem

**Comment by TriangleJuice** [comment]
Fixed in #40.
