### ISSUE TITLE
Can't import submodules in the styleguide

### ISSUE THREAD

**Issue by TriangleJuice** [digipolisantwerp/acpaas-ui_angular#27]
## Describe the bug
[Title says it all]

## To Reproduce
- Create an example page for the forms module, like you would do for any other module
- in the example: `import { AnySubModule } from '@acpaas-ui/ngx-components/main-module';` and add it to the `imports` from the example.
- run `npm run examples`

## Expected behavior
All examples should be build, but bow it gives an error on the import of the submodule (see below for details).

## Screenshots
N/A

## OS (please complete the following information):
 - Device: MacBook Pro (Retina, 15-inch, Early 2013)
 - OS: macOS X 10.13.6
 - Browser: N/A
 - Version: N/A

## Additional context
When running `npm run examples`, this is the error you get:

```
BUILD ERROR
: Unexpected value 'AutoCompleteModule in /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/dist/forms/forms.d.ts' imported by the module 'FormsExamplesModule in /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/packages/forms/examples/forms/forms.module.ts'. Please add a @NgModule annotation.

Error: : Unexpected value 'AutoCompleteModule in /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/dist/forms/forms.d.ts' imported by the module 'FormsExamplesModule in /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/packages/forms/examples/forms/forms.module.ts'. Please add a @NgModule annotation.

    at Object.<anonymous> (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

: Unexpected value 'AutoCompleteModule in /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/dist/forms/forms.d.ts' imported by the module 'FormsExamplesModule in /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/packages/forms/examples/forms/forms.module.ts'. Please add a @NgModule annotation.

Error: : Unexpected value 'AutoCompleteModule in /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/dist/forms/forms.d.ts' imported by the module 'FormsExamplesModule in /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/packages/forms/examples/forms/forms.module.ts'. Please add a @NgModule annotation.

    at Object.<anonymous> (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /Users/trianglejuice/Sites/Work/AUI/acpaas-ui_angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

**When running `npm run examples` without importing the submodule, there's no problem.**

**When importing the submodule in any other (independent) app, there's no problem.**

**Comment by TriangleJuice** [comment]
Fixed in #40.
